IMASD/Nomina2019/Models/ViewModels/tblEmpleados.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nomina2019.Models.ViewModels
{
    public class tblEmpleados
    {
        public int iIdEmpleado { get; set; }
        
        public int iIdentificadorEmpleado { get; set; }

        [Required]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Solo Puedes Capturar valores Numericos")]
        [Display(Name = "Sueldo Diario")]
        public decimal dSueldoDiario { get; set; }

        public tblPadronPersonas Padron { get; set;}
        
        public tblPeriodosPago PeriodoPago { get; set; }
        
        public tblDepartamentos Departamento { get; set; }
        
        public bool lActivo { get; set; }
        
        public DateTime dtCreacion { get; set; }
        
        public DateTime dtModificacion { get; set; }

        public IEnumerable<SelectListItem> lstPeriodosPago { get; set; }
        public IEnumerable<SelectListItem> lstDepartamentos { get; set; }
    }
}

IMASD/Nomina2019/Controllers/Empleados/tblEmpleadosController.cs
using Nomina2019.Data;
using Nomina2019.Models.SendModels;
//using Nomina2019.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Nomina2019.Controllers.Empleados
{
    public class tblEmpleadosController : Controller
    {
        // GET: tblEmpleados
        public async Task<ActionResult> Index(int iIdPeriodoPago = 0, int iIdDepartamento = 0)
        {
            var respuesta = new Nomina2019.Models.ViewModels.tblEmpleadoswithList();
            List <Models.ViewModels.tblEmpleados> lstEmpleados = new List<Models.ViewModels.tblEmpleados>();
            using (BDNOMINA2019Entities db = new BDNOMINA2019Entities())
            {
                var lstDepartamentosTMP = db.tblEmpleados.Select(x => new Models.ViewModels.tblEmpleados
                {
                    iIdEmpleado = x.iIdEmpleado,
                    Padron = new Models.ViewModels.tblPadronPersonas { 
                        cNombre = x.tblPadronPersonas.cNombre,
                        cApellido1 = x.tblPadronPersonas.cApellido1,
                        cApellido2 = x.tblPadronPersonas.cApellido2
                    },
                    Departamento = new Models.ViewModels.tblDepartamentos
                    {
                        iIdDepartamento = x.tblDepartamentos.iIdDepartamento,
                        cNombreDepartamento = x.tblDepartamentos.cNombreDepartamento
                    },
                    dSueldoDiario = (decimal)x.tblTabuladorSueldo.Where(w => (bool)w.lActivo).FirstOrDefault().dSueldoDiario,
                    PeriodoPago = new Models.ViewModels.tblPeriodosPago
                    {
                        iIdPeriodoPago = x.tblPeriodosPago.iIdPeriodoPago,
                        cNombrePeriodo = x.tblPeriodosPago.cNombrePeriodo,
                        iDiasxPeriodo = (int)x.tblPeriodosPago.iDiasxPeriodo
                    },
                    lActivo = (bool)x.lActivo,
                    dtCreacion = (DateTime)x.dtCreacion,
                    dtModificacion = (DateTime)x.dtModificacion
                }).Where(f=>f.lActivo).ToList();

                if (iIdPeriodoPago > 0 && iIdDepartamento > 0)
                {
                    lstEmpleados = lstDepartamentosTMP.Where(x => x.PeriodoPago.iIdPeriodoPago == iIdPeriodoPago && x.Departamento.iIdDepartamento == iIdDepartamento).ToList();
                }
                else
                {
                    if (iIdPeriodoPago > 0)
                    {
                        lstEmpleados = lstDepartamentosTMP.Where(x => x.PeriodoPago.iIdPeriodoPago == iIdPeriodoPago).ToList();
                    }
                    else
                    {
                        if (iIdDepartamento > 0)
                        {
                            lstEmpleados = lstDepartamentosTMP.Where(x => x.Departamento.iIdDepartamento == iIdDepartamento).ToList();
                        }
                        else
                        {
                            lstEmpleados = lstDepartamentosTMP;
                        }
                    }

                }


            }

            respuesta.lsttblEmpleados = lstEmpleados;
            respuesta.lstDepartamentos = await obtenerDepartamentos();
            respuesta.lstPeriodosPago = await obtenerPeriodosPago();

            return View(@"~/Views\tblEmpleados\tblEmpleados.cshtml", respuesta);
        }

        /// <summary>
        /// Metodo para optener los departamentos disponibles
        /// </summary>
        /// <returns></returns>
        private async Task<IEnumerable<SelectListItem>> obtenerDepartamentos()
        {
            
            using (BDNOMINA2019Entities db = new BDNOMINA2019Entities())
            {
                var departamentos = db
                            .tblDepartamentos
                            .Select(x =>
                                    new SelectListItem
                                    {
                                        Value = x.iIdDepartamento.ToString(),
                                        Text = x.cNombreDepartamento
                                    }).ToList();

                return new SelectList(departamentos, "Value", "Text");
            }
        }

        /// <summary>
        /// Metodo para optener los periodos de pago disponibles
        /// </summary>
        /// <returns></returns>
        private async Task<IEnumerable<SelectListItem>> obtenerPeriodosPago()
        {

            using (BDNOMINA2019Entities db = new BDNOMINA2019Entities())
            {
                var periodos = db
                            .tblPeriodosPago
                            .Select(x =>
                                    new SelectListItem
                                    {
                                        Value = x.iIdPeriodoPago.ToString(),
                                        Text = x.cNombrePeriodo
                                    }).ToList();

                return new SelectList(periodos, "Value", "Text");
            }
        }


        /// <summary>
        /// Metodo de carga de la vista Nuevo
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Nuevo()
        {
            var objEmpleados = new Models.ViewModels.tblEmpleados();
            objEmpleados.lstDepartamentos = await obtenerDepartamentos();
            objEmpleados.lstPeriodosPago = await obtenerPeriodosPago();

            return View(@"~/Views\tblEmpleados\Nuevo.cshtml",objEmpleados);
        }


        /// <summary>
        /// Metodo para crear un nuevo empleado
        /// </summary>
        /// <param name="_empleado"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Nuevo(Models.ViewModels.tblEmpleados _empleado)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    using (BDNOMINA2019Entities db = new BDNOMINA2019Entities())
                    {
                        var respuesta = db.empleados_crud(
                                        0/*identificador empleado vacio*/,
                                        _empleado.Padron.iIdPadron,
                                        _empleado.Padron.cNombre,
                                        _empleado.Padron.cApellido1,
                                        _empleado.Padron.cApellido2,
                                        _empleado.Padron.cDireccion,
                                        _empleado.Padron.cTelefono,
                                        _empleado.PeriodoPago.iIdPeriodoPago,
                                        _empleado.Departamento.iIdDepartamento,
                                        _empleado.dSueldoDiario,
                                        1/*validador Crear Nuevo*/);
                    }
                    return Redirect("../tblempleados");
                }


                _empleado.lstDepartamentos = await obtenerDepartamentos();
                _empleado.lstPeriodosPago = await obtenerPeriodosPago();
                return View(_empleado);


            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }


        /// <summary>
        /// Metodo de carga de la vista Editar
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Editar(int Id)
        {
            var objEmpleados = new Models.ViewModels.tblEmpleados();

            using (BDNOMINA2019Entities db = new BDNOMINA2019Entities())
            {
                List<Models.ViewModels.tblEmpleados> lstTblEmpleados = db.tblEmpleados.Select(x => new Models.ViewModels.tblEmpleados
                {
                    iIdEmpleado = x.iIdEmpleado,
                    Padron = new Models.ViewModels.tblPadronPersonas
                    {
                        iIdPadron = x.tblPadronPersonas.iIdPadron,
                        cNombre = x.tblPadronPersonas.cNombre,
                        cApellido1 = x.tblPadronPersonas.cApellido1,
                        cApellido2 = x.tblPadronPersonas.cApellido2,
                        cDireccion = x.tblPadronPersonas.cDireccion,
                        cTelefono = x.tblPadronPersonas.cTelefono
                    },
                    Departamento = new Models.ViewModels.tblDepartamentos
                    {
                        iIdDepartamento = x.tblDepartamentos.iIdDepartamento,
                        cNombreDepartamento = x.tblDepartamentos.cNombreDepartamento
                    },
                    dSueldoDiario = (decimal)x.tblTabuladorSueldo.Where(w => (bool)w.lActivo).FirstOrDefault().dSueldoDiario,
                    PeriodoPago = new Models.ViewModels.tblPeriodosPago
                    {
                        iIdPeriodoPago = x.tblPeriodosPago.iIdPeriodoPago,
                        cNombrePeriodo = x.tblPeriodosPago.cNombrePeriodo,
                        iDiasxPeriodo = (int)x.tblPeriodosPago.iDiasxPeriodo
                    },
                    lActivo = (bool)x.lActivo,
                    dtCreacion = (DateTime)x.dtCreacion,
                    dtModificacion = (DateTime)x.dtModificacion
                }).Where(f => f.lActivo && f.iIdEmpleado == Id).ToList();

                objEmpleados = lstTblEmpleados.FirstOrDefault();
                objEmpleados.lstDepartamentos = await obtenerDepartamentos();
                objEmpleados.lstPeriodosPago = await obtenerPeriodosPago();

            }
            
            return View(@"~/Views\tblEmpleados\Editar.cshtml", objEmpleados);

        }


        /// <summary>
        /// Metodo para editar un empleado
        /// </summary>
        /// <param name="_empleado"></param>
        /// <returns></returns>
        [HttpPost]

IMASD/Nomina2019/Views/tblEmpleados/Editar.cshtml
@model Nomina2019.Models.ViewModels.tblEmpleados
@{
    ViewBag.Title = "Editar";
}

<h2>Editar Empleado</h2>

@using (Html.BeginForm("Editar", "tblEmpleados", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(m => m.iIdEmpleado)
            @Html.HiddenFor(m => m.Padron.iIdPadron)
            <div>
                @Html.Label("Nombre")
                @Html.TextBoxFor(n => n.Padron.cNombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cNombre, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Apellido Paterno")
                @Html.TextBoxFor(n => n.Padron.cApellido1, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cApellido1, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Apellido Materno")
                @Html.TextBoxFor(n => n.Padron.cApellido2, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cApellido2, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Dirección")
                @Html.TextBoxFor(n => n.Padron.cDireccion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cDireccion, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Telefono")
                @Html.TextBoxFor(n => n.Padron.cTelefono, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cTelefono, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Departamento")
                @Html.DropDownListFor(m => m.Departamento.iIdDepartamento, Model.lstDepartamentos, new { @class = "form-control" })
            </div>
            <br />
            <div>
                @Html.Label("Período De Pago")
                @Html.DropDownListFor(m => m.PeriodoPago.iIdPeriodoPago, Model.lstPeriodosPago, new { @class = "form-control" })
            </div>
            <br />
            <div>
                @Html.Label("Sueldo Diario")
                @Html.TextBoxFor(n => n.dSueldoDiario, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.dSueldoDiario, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div style="text-align:right">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>


}

IMASD/Nomina2019/Views/tblEmpleados/Nuevo.cshtml
@model Nomina2019.Models.ViewModels.tblEmpleados
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo Empleado</h2>

@using (Html.BeginForm("Nuevo", "tblEmpleados", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.Label("Nombre")
                @Html.TextBoxFor(n => n.Padron.cNombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cNombre, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Apellido Paterno")
                @Html.TextBoxFor(n => n.Padron.cApellido1, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cApellido1, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Apellido Materno")
                @Html.TextBoxFor(n => n.Padron.cApellido2, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cApellido2, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Dirección")
                @Html.TextBoxFor(n => n.Padron.cDireccion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cDireccion, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Telefono")
                @Html.TextBoxFor(n => n.Padron.cTelefono, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.Padron.cTelefono, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div>
                @Html.Label("Departamento")
                @Html.DropDownListFor(m => m.Departamento.iIdDepartamento, Model.lstDepartamentos, new { @class = "form-control" })
            </div>
            <br />
            <div>
                @Html.Label("Período De Pago")
                @Html.DropDownListFor(m => m.PeriodoPago.iIdPeriodoPago, Model.lstPeriodosPago, new { @class = "form-control" })
            </div>
            <br />
            <div>
                @Html.Label("Sueldo Diario")
                @Html.TextBoxFor(n => n.dSueldoDiario, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(n => n.dSueldoDiario, null, new { @class = "alertaroja" })
            </div>
            <br />
            <div style="text-align:right">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>


}

IMASD/Nomina2019/Views/tblEmpleados/tblEmpleados.cshtml
@model Nomina2019.Models.ViewModels.tblEmpleadoswithList
@{
    ViewBag.Title = "tblEmpleados";
}

<h2>Empleados</h2>

<div class="row" style="text-align:right; padding:5px;">
    <a href="~/tblEmpleados/Nuevo" class="btn btn-primary">Registrar Nuevo Empleado</a>
</div>
<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm("Index", "tblEmpleados", FormMethod.Get))
        {
            <label>SELECCIONE UN DEPARTAMENTO</label>
            @Html.DropDownListFor(f => f.iIdDepartamento, Model.lstDepartamentos, "Sin Filtro")

            <label>SELECCIONE UN PERIODO DE PAGO</label>
            @Html.DropDownListFor(f => f.iIdPeriodoPago, Model.lstPeriodosPago, "Sin Filtro")
            <input type="submit" value="Buscar" />
        }
        <br />
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Departamento</th>
                <th>Período de pago</th>
                <th>Sueldo Diario</th>
                <th>Sueldo Por Período</th>
                <th>Fecha de Creación</th>
                <th>Fecha de Modificación</th>
                <th></th>
            </tr>
            @foreach (var _empleado in Model.lsttblEmpleados)
            {
                <tr>
                    <td>@_empleado.iIdEmpleado</td>
                    <td>@string.Format("{0} {1} {2}", _empleado.Padron.cNombre, _empleado.Padron.cApellido1, _empleado.Padron.cApellido2)</td>
                    <td>@_empleado.Departamento.cNombreDepartamento </td>
                    <td>@_empleado.PeriodoPago.cNombrePeriodo </td>
                    <td>@_empleado.dSueldoDiario </td>
                    <td>@string.Format("$ {0}", (_empleado.dSueldoDiario * _empleado.PeriodoPago.iDiasxPeriodo))</td>
                    <td>@string.Format("{0}",_empleado.dtCreacion.ToShortDateString())</td>
                    <td>@string.Format("{0}",@_empleado.dtModificacion.ToShortDateString())</td>
                    <td>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="~/tblEmpleados/Editar/@_empleado.iIdEmpleado" class="btn btn-default">Editar</a>
                            </div>
                            <div class="col-md-6">
                                <a href="~/tblEmpleados/Eliminar/@_empleado.iIdEmpleado" class="btn btn-danger">Eliminar</a>
                            </div>
                        </div>
                        
                       
                    </td>
                </tr>
            }
        </table>
    </div>

</div>